### ISSUE TITLE
Look for an alernative to CentOS for upgrading to RHEL 8 base

### ISSUE THREAD

**Issue by JPvRiel** [JPvRiel/docker-rsyslog#7]
IBM seem to have forced CentOS into a beta release channel, which no longer matches RHEL 8 stable versions.

Alma Linux could provide an alternative.

**Comment by rgerhards** [comment]
Did you consider [Rocky Linux](https://rockylinux.org/)? I have no real opinion on it, but stumbled over it when I needed to replace CentOS 8 in rsyslog CI.

**Comment by JPvRiel** [comment]
> Did you consider [Rocky Linux](https://rockylinux.org/)? I have no real opinion on it, but stumbled over it when I needed to replace CentOS 8 in rsyslog CI.

Thanks, tried Rocky. Been using AlmaLinux nicely on other projects. But ran into this issue either way: https://github.com/rsyslog/rsyslog/issues/4966

So both RockyLinux and AlmaLinux seem like solid options ([AlmaLinux vs Rocky Linux 2022: This Will Help You Decide!](https://cloudzy.com/almalinux-vs-rocky-linux/)), and both have the same issue with librdkafka.

**Comment by JPvRiel** [comment]
Upstream packaging fix from https://github.com/rsyslog/rsyslog/issues/4966 allowed for switching from CentOS 7  to Alma Linux 8 done with cc6e359f6d8300a3b26856094f8a6c5d35a58607 which now re bases the container on a more modern/patched RHEL related distro.

Image size is also almost halved by using `almalinux:8-minimal` as the base. However, needing to install python for some troubleshooting config scripts adds a bit of bloat.
